### DOCS: https://github.com/Huachao/vscode-restclient#making-graphql-request

@baseUrl = http://{{$dotenv APP_HOST}}:{{$dotenv APP_PORT}}/graphql
@auth_token = {{$dotenv JWT_AUTH_TOKEN}}

######################
### Deletes a painting
# @name DeletePainting

POST {{ baseUrl }}
Content-Type: application/json
Authorization: Bearer {{ auth_token }}
X-REQUEST-TYPE: GraphQL

mutation DeletePainting($paintingId: String!) {
  deletePainting(id: $paintingId) {
    message
  }
}

### variables
{
  "paintingId": "65735fa9a378824bf2347bf5"
}
