### DOCS: https://github.com/Huachao/vscode-restclient#making-graphql-request

@baseUrl = http://{{$dotenv APP_HOST}}:{{$dotenv APP_PORT}}/graphql

######################
### Create a new user successfully
# @name SignupUser

POST {{ baseUrl }}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation SignupUser($input: SignupInput!) {
  signup(input: $input) {
    message
    result {
      _id
      email
      fullname
      jwtoken
      createdAt
    }
  }
}

### variables
{
  "input": {
    "fullname": "Pablo Picasso",
    "email": "pablo.picasso@domain.com",
    "password": "zqEgVcURzKmsm9h"
  }
}
