@app_port = {{$dotenv APP_PORT}}

POST http://localhost:{{app_port}}/api/v1/paintings?t={{$timestamp}}
Content-Type: application/json
User-Agent: Aldous-Huxley-v1.0

{
  "name": "Oil Painting Techniques And Styles",
  "url": "https://artignition.com/oil-painting-techniques/",
  "techniques": ["Glazing", "Wet-on-Wet", "Blending", "Scumbling"]
}

# ---

GET http://localhost:{{app_port}}/api/v1/paintings?page=1
Content-Type: application/json

GET http://localhost:{{app_port}}/api/v1/paintings/1/?limit=3
Content-Type: application/json

# ---

GET http://localhost:{{app_port}}/healthcheck
Content-Type: application/json
